name: mrtf
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - numpy>=1.23
  - matplotlib>=3.7
  - tqdm>=4.66
  - pytorch>=2.1
  - torchvision>=0.16
  - pip:
      - shap>=0.44
      - librosa>=0.10
      - soundfile>=0.12
      - nibabel>=5.2
      - scikit-image>=0.22
      - pywavelets>=1.5
